# Example nginx config for serving the exported `out` folder.
# Vercel does not need this file. It uses `api/contact.js` automatically.

server {
  server_name swaram.ae www.swaram.ae;

  root /var/www/swaram/out;
  index index.html;

  location = /api/contact {
    proxy_pass https://api.ayatiworks.com/api/v1/public/swaram/contact_us/records;
    proxy_http_version 1.1;
    proxy_ssl_server_name on;

    proxy_set_header Host api.ayatiworks.com;
    proxy_set_header Content-Type application/json;
    proxy_set_header X-API-Key "f5a4ee7d75445be656bd8529c143b2567a3eeedfdcdfa6cbac5652f0a3f92289";
  }

  location / {
    try_files $uri $uri/ $uri.html /404.html;
  }
}
